In [5]:
# Import Library

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,cross_validate,cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [6]:
# Loading the dataset
df = pd.read_csv("heart_disease.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,57,1,0,119,182,0,1,153,1,1.0,2,2,2,1
1,44,1,2,123,170,0,0,171,0,0.3,2,0,3,0
2,61,0,0,138,211,0,0,147,0,0.2,1,0,3,1
3,63,1,3,105,277,0,0,143,0,0.5,0,0,3,1
4,35,1,0,98,122,0,0,176,0,2.2,2,1,3,0

In [7]:
# basic info

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12234 entries, 0 to 12233
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       12234 non-null  int64
 1   sex       12234 non-null  int64
 2   cp        12234 non-null  int64
 3   trestbps  12234 non-null  int64
 4   chol      12234 non-null  int64
 5   fbs       12234 non-null  int64
 6   restecg   12234 non-null  int64
 7   thalach   12234 non-null  int64
 8   exang     12234 non-null  int64
 9   oldpeak   12234 non-null  float64
 10  slope     12234 non-null  int64
 11  ca        12234 non-null  int64
 12  thal      12234 non-null  int64
 13  target    12234 non-null  int64
dtypes: float64(1), int64(13)
memory usage: 1.3 MB

In [8]:
# find null values

df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [9]:
# duplicat row

df.duplicated().sum()

np.int64(0)

In [10]:
x = df.drop("target",axis = 1)
y = df["target"]

In [11]:
# Splitting the dataset for training and testing

x_train ,x_test ,y_train ,y_test = train_test_split(
    x,y,test_size = 0.3,random_state = 40
)

In [12]:
print("Training Data shape : ", x_train.shape)
print("Testing Data shape : ", x_test.shape)

Training Data shape :  (8563, 13)
Testing Data shape :  (3671, 13)

In [13]:
# Model Training
LR = LogisticRegression(max_iter=1000)
LR.fit(x_train ,y_train)

LogisticRegression(max_iter=1000)

In [14]:
# Testing Accuracy
y_pred = LR.predict(x_test)
accuracy = accuracy_score(y_pred, y_test)
print("Testing Accuracy : ", accuracy)

Testing Accuracy :  0.8613456823753746

In [15]:
# Traning Accuracy
y_pred_train = LR.predict(x_train)
accuracy_train = accuracy_score(y_pred_train, y_train)
print("Testing Accuracy : ", accuracy_train)

Testing Accuracy :  0.8738759780450777

In [16]:
# validation accuracy

val_accuracy = cross_val_score(
    LR,x_train ,y_train ,cv=5
)

print("Validation Accuracy : ",val_accuracy.mean())

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Validation Accuracy :  0.872473484786487

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [17]:
# Random Forest Clasiiifier
RF = RandomForestClassifier(
    n_estimators = 200,max_depth = 10,min_samples_leaf=10,verbose=1,n_jobs=1
)

In [18]:
RF.fit(x_train,y_train)

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.4s
[Parallel(n_jobs=1)]: Done 199 tasks      | elapsed:    1.8s
[Parallel(n_jobs=1)]: Done 200 out of 200 | elapsed:    1.9s finished

RandomForestClassifier(max_depth=10, min_samples_leaf=10, n_estimators=200,
                       n_jobs=1, verbose=1)

In [19]:
# Testing Accuracy of Random Forest
y_pred_rf = RF.predict(x_test)
accuracy_rf = accuracy_score(y_pred_rf, y_test)
print("Testing Accuracy : ", accuracy_rf)

Testing Accuracy :  0.8937619177335876

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 199 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done 200 out of 200 | elapsed:    0.1s finished

In [20]:
# Traning Accuracy of Random Forest
y_pred_train_rf= RF.predict(x_train)
accuracy_train_rf = accuracy_score(y_pred_train_rf, y_train)
print("Testing Accuracy : ", accuracy_train_rf)

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.1s

Testing Accuracy :  0.9383393670442602

[Parallel(n_jobs=1)]: Done 199 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done 200 out of 200 | elapsed:    0.2s finished

In [21]:
# GradientBoostingClassifier

gb = GradientBoostingClassifier(
    n_estimators=200 , min_samples_leaf= 10 ,learning_rate=0.1 ,random_state=42
)

gb.fit(x_train ,y_train)

GradientBoostingClassifier(min_samples_leaf=10, n_estimators=200,
                           random_state=42)

In [22]:
# Testing Accuracy of Gardient Boosting
y_pred_gb =gb.predict(x_test)
accuracy_gb = accuracy_score(y_pred_gb, y_test)
print("Testing Accuracy : ", accuracy_gb)

Testing Accuracy :  0.929719422500681

In [23]:
# Traning Accuracy of Gardient Boosting
y_pred_train_gb= gb.predict(x_train)
accuracy_train_gb = accuracy_score(y_pred_train_gb, y_train)
print("Testing Accuracy : ", accuracy_train_gb)

Testing Accuracy :  0.9633306084316244

In [25]:
valid_gb = cross_val_score(
    gb,x_train,y_train ,cv = 5
)

print("Validation Accuracy : ", valid_gb.mean())

Validation Accuracy :  0.9284126061836098

In [39]:
confusion_matrix(y_pred_gb,y_test)

array([[1721,  135],
       [ 123, 1692]])

In [26]:
pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (3.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost) (1.16.3)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.32.3)

In [36]:
# Xgboost Algorithm

from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators = 100,max_depth = 5,learning_rate= 0.2,random_state = 35
)

xgb.fit(x_train , y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.2, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [37]:
# Testing Accuracy of XGB Boosting
y_pred_xgb =xgb.predict(x_test)
accuracy_xgb = accuracy_score(y_pred_xgb, y_test)
print("Testing Accuracy : ", accuracy_xgb)

Testing Accuracy :  0.925088531735222

In [38]:
# Traning Accuracy of XGB Boosting
y_pred_train_xgb= xgb.predict(x_train)
accuracy_train_xgb = accuracy_score(y_pred_train_xgb, y_train)
print("Testing Accuracy : ", accuracy_train_xgb)

Testing Accuracy :  0.9864533457900269

In [42]:
import joblib

joblib.dump({"model":gb,"features":list(x.columns)},"heart.joblib",compress=3)

['heart.joblib']